# Module 3 | Matrices

### Create and naming matrices

In [3]:
matrix(1:6, nrow=2)                 # Simple matrix

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [4]:
matrix(1:6, ncol=2, byrow=TRUE)     # Interesting form of matrix

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [21]:
# cbind and rbind
rbind(1:3, 3:5)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 3    4    5

In [6]:
cbind(1:3, 1:3)

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3

In [17]:
simple_matrix <- matrix(
    1:4, 
    byrow=TRUE, 
    nrow=2, 
    dimnames = list(c("row 1", "row 2"), c("col1", "col2"))
)

simple_matrix

col1 col2
row 1 1    2   
row 2 3    4

In [18]:
matrix(1:4, nrow=40)

[,1]
 [1,] 1   
 [2,] 2   
 [3,] 3   
 [4,] 4   
 [5,] 1   
 [6,] 2   
 [7,] 3   
 [8,] 4   
 [9,] 1   
[10,] 2   
[11,] 3   
[12,] 4   
[13,] 1   
[14,] 2   
[15,] 3   
[16,] 4   
[17,] 1   
[18,] 2   
[19,] 3   
[20,] 4   
[21,] 1   
[22,] 2   
[23,] 3   
[24,] 4   
[25,] 1   
[26,] 2   
[27,] 3   
[28,] 4   
[29,] 1   
[30,] 2   
[31,] 3   
[32,] 4   
[33,] 1   
[34,] 2   
[35,] 3   
[36,] 4   
[37,] 1   
[38,] 2   
[39,] 3   
[40,] 4

### Matrix Subsetting

In [30]:
m_matrix <- matrix(1:3, 3, 3)
m_matrix

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 2    2    2   
[3,] 3    3    3

In [34]:
rownames(m_matrix) <- c("row1", "row2", "row3")
colnames(m_matrix) <- c("col1", "col2", "col3")
m_matrix

col1 col2 col3
row1 1    1    1   
row2 2    2    2   
row3 3    3    3

### Matrix Arthimetic

In [35]:
m_matrix * 4.25

col1  col2  col3 
row1  4.25  4.25  4.25
row2  8.50  8.50  8.50
row3 12.75 12.75 12.75